### ISSUE TITLE
Checkboxes in todoMVC example are not visible

### ISSUE THREAD

**Issue by akkartik** [fpereiro/gotoB#4]
I can click to the left of items to cross them out. But I can't see the checkboxes, on either Firefox or Chrome on Mac OS. Is this intentional?

<img width="1318" alt="Screen Shot 2020-07-12 at 8 11 27 PM" src="https://user-images.githubusercontent.com/3161/87267284-0bbac600-c47c-11ea-95ec-7b37d6fe095d.png">

**Comment by fpereiro** [comment]
This is definitely a bug; thanks for posting it!

I just updated the CSS (https://github.com/fpereiro/gotoB/commit/5045102854898c94e9dc440b67cee8ef09e05b06) and the bug seems to be fixed; this will be included in an upcoming release for v1. Will reply again when the release is published.

**Comment by fpereiro** [comment]
Hi @akkartik ! Just fixed this in v1.2.5. Can you confirm it looks good on your end?

**Comment by akkartik** [comment]
Confirmed!

**Comment by fpereiro** [comment]
Thank you!!

пт, 17 июл. 2020 г. в 03:29, Kartik Agaram <notifications@github.com>:
